# visit https://github.com/mojombo/jekyll/wiki/Configuration for more settings

paginate: 10 # pagination based on number of posts
paginate_path: "page:num"
exclude: ["README.md"] # files to exclude
highlighter: pygments
markdown: kramdown
disqus: dbyll
google_analytics: kael

defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      title: 逝水流年，不变初心，方得始终。

description: Stylish Jekyll Theme
author:
  name: Kael
  email: kael.li1122@gmail.com
  github: kaelli1234
  weibo: codingggggg
  twitter: 
  pinterest: 
  linkedin: 
  bio: '不乱于心，不困于情。不畏将来，不念过往。'
  email_md5: 726351295ec82e145928582f595aa3aa

rss_path: feed.xml
categories_path: categories.html
about_path: about.html
tags_path: tags.html

BASE_PATH:
